Repository taniarascia/takenote, pull requests merged in 2019-10, with the labels that each got.

#37 Make bottom icon buttons accessible
  src/containers/AppSidebar.tsx
  src/styles/_sidebars.scss
Labels: enhancement

#44 Use absolute URL for issues link
  README.md
Labels: documentation

#45 Add @meowwwls, @jjtowle as contributors; add all-contribs script
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: documentation

#68 swap the alt and ctrl shortcuts
  src/containers/SettingsModal.tsx
Labels: enhancement

#80 Create React Event types
  src/containers/AppSidebar.tsx
  src/containers/NoteList.tsx
  src/containers/SettingsModal.tsx
  src/types/index.ts
Labels: Type: Refactor

#81 Create AppSidebarAction component
  src/components/AppSidebarAction.tsx
  src/constants/index.ts
  src/containers/AppSidebar.tsx
Labels: Type: Refactor

#88 Feature added - Toggle Line Highlight
  src/containers/SettingsModal.tsx
Labels: Type: Feature

#86 fix(keyboard-shortcuts): dispatch CodeMirror theme change with DarkMode shortcut
  src/containers/KeyboardShortcuts.tsx
  src/containers/SettingsModal.tsx
Labels: Type: Bug

#79 Allow the app to run in Docker
  .dockerignore
  Dockerfile
  README.md
Labels: Type: Feature

#102 Add relavant fields to package.json
  package.json
Labels: Type: Refactor

#103 Feature: Auto reload after injecting seed
  README.md
  seed.js
Labels: Type: Feature

#64 Enable categories to be renamed by double clicking on them.
  src/containers/AppSidebar.tsx
Labels: Type: Feature

#101 Feature added - Detect when vim is in edit mode
  src/containers/NoteEditor.tsx
  src/slices/settings.ts
  src/styles/_editor.scss
  src/types/index.ts
Labels: Type: Feature

#125 feat(cypress-e2e): add category tests, add cypress-testing-library
  cypress/integration/category.spec.ts
  cypress/support/commands.js
  cypress/support/index.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  src/containers/AppSidebar.tsx
Labels: Type: Testing

#118 Fix getNoteTitle for non-latin symbols
  src/helpers/index.ts
Labels: Type: Bug

#124 fix empty category name
  src/containers/AppSidebar.tsx
Labels: Type: Bug

#126 Fix note-list overflow
  src/containers/NoteList.tsx
  src/styles/_note-sidebar.scss
Labels: Type: Bug

#121 Feature - Makes favorites sit at the top of the notes list
  src/containers/NoteList.tsx
  src/helpers/index.ts
  src/slices/note.ts
  src/styles/_note-sidebar.scss
Labels: Status: Needs work, Type: Feature

#134 Improve NoteOptions a11y
  src/components/NoteOptionsButton.tsx
  src/containers/NoteOptions.tsx
Labels: Type: Accessibility

#136 Add a11y linting script
  a11y.json
  package.json
Labels: Type: Accessibility
