Repository taniarascia/takenote, pull requests merged in 2020-01, with the labels that each got.

#215 Cleaned up newNoteHandler duplicated code and moved to helper file
  src/containers/AppSidebar.tsx
  src/containers/KeyboardShortcuts.tsx
  src/helpers/index.ts
  src/types/index.ts
Labels: Status: Completed, Type: Refactor

#214 Added some test framework and new tests.
  cypress/integration/category.spec.ts
  cypress/integration/note.spec.ts
  cypress/integration/utils/testCategoryHelperUtils.ts
  cypress/integration/utils/testHelperEnums.ts
  cypress/integration/utils/testHelperUtils.ts
  cypress/integration/utils/testNotesHelperUtils.ts
  src/components/AppSidebarAction.tsx
  src/components/NoteListButton.tsx
  src/components/NoteOptionsButton.tsx
  src/containers/AppSidebar.tsx
  src/containers/NoteList.tsx
  src/containers/NoteOptions.tsx
Labels: Status: Completed, Type: Testing

#142 Show welcome note for new users
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  src/api/index.ts
  src/api/welcomeNote.ts
  src/react-app-env.d.ts
  src/styles/_note-sidebar.scss
  src/welcomeNote.md
Labels: Type: Feature
